### ISSUE TITLE
Just a question about roles and permissions

### ISSUE THREAD

**Issue by PanArnaud** [zaknes/zak#1]
Hi !

I just forked your project. You works are nice ! 
But I have a question : What's the difference between "roles" and "permissions" please ? Actually, I'm trying to install your forum and I can't register because of my database don't have role. 

I think I understand that "user" or "admin" are roles.

**Comment by PanArnaud** [comment]
Wrong repository sorry.

**Comment by zaknes** [comment]
Oh haha it's okay!

I recommend reading the documentation for [Entrust](https://github.com/Zizaco/entrust). It's awesome.

The difference between the two is that Roles are the actual user groups, so for example user, moderator, admin, owner, etc.

Permissions are individual permissions that are used to check; this way a user group can get a specific permission without a complete change of groups.

An example of the above is that if a user needs a "delete-post" permission, he or she can just have access to that node specifically, rather than having a new user role (group).

**Comment by PanArnaud** [comment]
Thank you ! I will reading it !
And if you're agree, I could help you to build this app. I could learn a lot (I did too reading your code!!) and I hope you too.

Sorry for my english :O
